### ISSUE TITLE
Can I make any scene, character, or action I want?

### ISSUE THREAD

**Issue by onlyonewater** [xavierpuigf/virtualhome_unity#10]
Can I make any scenes, characters, or actions I want in this repo?

**Comment by kswain98** [comment]
Hi! @onlyonewater! Yes you can!

**Comment by onlyonewater** [comment]
hi, @kswain98 , thank you for your reply. Is there any documentation on how to do this？

**Comment by kswain98** [comment]
You can visit this directory which should give a good overview of how to get started with the master branch: https://github.com/xavierpuigf/virtualhome_unity/tree/master/doc

We are giving VirtualHome a slight overhaul in one day. If you want and are free, I can give a quick intro of how to get everything started via zoom if the current documentation is missing something, or if you have any other question.
