### ISSUE TITLE
Does this project need the plug-in of Final IK？

### ISSUE THREAD

**Issue by Treeloveswater** [xavierpuigf/virtualhome_unity#18]
Does this project need the plug-in of Final IK？

There are many errors after opening the project

Like：
Assets\Story Generator\Animator\Scripts\BlendHandRelativePos.cs(1,7): error CS0246: The type or namespace name 'RootMotion' could not be found (are you missing a using directive or an assembly reference?)

Does this project need the plug-in of Final IK？

**Comment by MicroSTM** [comment]
Yes. Please refer to this document for third-party assets: https://github.com/xavierpuigf/virtualhome_unity/blob/5fda350cb960b2f3e0388cd6165554d74f7d9f0d/doc/third_party.md
