### ISSUE TITLE
Failed to load NavMesh.asset because it was serialized with a newer version of Unity.

### ISSUE THREAD

**Issue by simonobi** [xavierpuigf/virtualhome_unity#8]
Hello
I opened the latest version of master in unity 2018.4.4 and whenever I open a test scene I encounter errors similar to this one:
**Failed to load 'D:/Code/virtualhome_unity/Assets/Story Generator/TestScene/TestScene_6/NavMesh.asset' because it was serialized with a newer version of Unity. (Has a higher SerializedFile version)**

One of the authors mentioned that the latest build was made using 2019.X.
Can you please specify the exact unity version that was used ?

Also, you should update the documentation and specify to open the project in unity 2019.X and not in 2018.4.

Thank you

**Comment by kswain98** [comment]
Hi @simonobi! The current codebase uses Unity 2019.4.29 LTS. I will be updating the documents this week, thank you for letting me know!
